server:
  port: 0
spring:
  application:
    name: product-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product_service_db
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /api-docs/swagger-ui.html
    tagsSorter: alpha
